import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <nav className="h-16 fixed top-0 w-full z-10 flex justify-between">
            <div className="px-8 py-2 w-full h-full flex items-center justify-between">
              <Link href="/">Stickers AI</Link>
            </div>
          </nav>
          <main className="flex-1 overflow-y-auto mt-16 px-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
